select
    id,
    is_deleted,
    nullif(trim(last_name), '') as primary_contact_last_name,
    nullif(trim(first_name), '') as primary_contact_first_name,
    nullif(trim(title), '') as title,
    nullif(trim(company), '') as company,
    nullif(trim(street), '') as street_address,
    nullif(trim(city), '') as address_city,
    nullif(trim(state), '') as address_state,
    split_part(nullif(trim(postal_code), ''), '-', 1) as postal_code,
    nullif(trim(country), '') as country,
    phone,
    mobile_phone,
    nullif(trim(email), '') as email,
    nullif(trim(website), '') as website,
    nullif(trim(lead_source), '') as lead_source,
    nullif(trim(status), '') as status,
    is_converted,
    created_date as created_at,
    created_date::date as created_date,
    last_modified_date as last_modified_at,
    last_modified_date::date as last_modified_date,
    last_activity_date,
    last_viewed_date,
    last_referenced_date,
    email_bounced_reason,
    email_bounced_date,
    nullif(trim(outreach_stage_c), '') as outreach_stage,
    current_enrollment_c as current_enrollment,
    capacity_c as capacity,
    lead_source_last_updated_c as lead_source_last_updated_at,
    brightwheel_school_uuid_c as brightwheel_school_uuid
from {{ ref('salesforce_leads') }}
qualify row_number() over (partition by phone order by created_at asc) = 1
